require('dotenv').config();
const { PrismaPg } = require('@prisma/adapter-pg');
const { PrismaClient } = require('@prisma/client');
const { Pool } = require('pg');

const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error('DATABASE_URL is required to run the seed script.');
}

const pool = new Pool({ connectionString: databaseUrl });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function seed() {
  console.log('🌱 Seeding database...');

  // Clear existing data (development only)
  await prisma.searchLog.deleteMany();
  await prisma.tireVariant.deleteMany();
  await prisma.tireCode.deleteMany();
  await prisma.tireSize.deleteMany();

  // Reset sequence to 100
  await prisma.$executeRawUnsafe("SELECT setval('tire_code_seq', 100, false);");

  // Tire sizes with their mappings (codes are auto-generated)
  const tireSizes = [
    { sizeRaw: '205/55R16', sizeNormalized: '205/55R16', width: 205, aspectRatio: 55, rimDiameter: 16 },
    { sizeRaw: '195/65R15', sizeNormalized: '195/65R15', width: 195, aspectRatio: 65, rimDiameter: 15 },
    { sizeRaw: '215/60R16', sizeNormalized: '215/60R16', width: 215, aspectRatio: 60, rimDiameter: 16 },
    { sizeRaw: '225/45R17', sizeNormalized: '225/45R17', width: 225, aspectRatio: 45, rimDiameter: 17 },
    { sizeRaw: '235/50R18', sizeNormalized: '235/50R18', width: 235, aspectRatio: 50, rimDiameter: 18 },
    { sizeRaw: '245/40R18', sizeNormalized: '245/40R18', width: 245, aspectRatio: 40, rimDiameter: 18 },
    { sizeRaw: '255/55R19', sizeNormalized: '255/55R19', width: 255, aspectRatio: 55, rimDiameter: 19 },
    { sizeRaw: '265/70R17', sizeNormalized: '265/70R17', width: 265, aspectRatio: 70, rimDiameter: 17 },
  ];

  for (const { sizeRaw, sizeNormalized, width, aspectRatio, rimDiameter } of tireSizes) {
    const tireSize = await prisma.tireSize.create({
      data: {
        sizeRaw,
        sizeNormalized,
        width,
        aspectRatio,
        rimDiameter,
      },
    });

    // Create corresponding tire code (code is auto-generated by DB sequence)
    const tireCode = await prisma.tireCode.create({
      data: {
        tireSizeId: tireSize.id,
        // codePublic is auto-generated starting from 100
      },
    });

    console.log(`✓ Created: ${sizeNormalized} → ${tireCode.codePublic} (auto-generated)`);
  }

  // Add some variants (LI/SI) for specific sizes
  const firstSize = await prisma.tireSize.findUnique({
    where: { sizeNormalized: '205/55R16' },
  });

  if (firstSize) {
    await prisma.tireVariant.create({
      data: {
        tireSizeId: firstSize.id,
        loadIndex: 91,
        speedIndex: 'V',
      },
    });
    console.log('✓ Created variant: 205/55R16 91V');

    await prisma.tireVariant.create({
      data: {
        tireSizeId: firstSize.id,
        loadIndex: 94,
        speedIndex: 'W',
      },
    });
    console.log('✓ Created variant: 205/55R16 94W');
  }

  console.log('\n✅ Seed completed successfully!');
}

seed()
  .catch((error) => {
    console.error('❌ Seed failed:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
