import {
  Controller,
  Post,
  Patch,
  Delete,
  Get,
  Body,
  Param,
  UseInterceptors,
  UploadedFile,
  BadRequestException,
} from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import { SkipThrottle } from '@nestjs/throttler';
import {
  ApiTags,
  ApiOperation,
  ApiParam,
  ApiResponse,
  ApiCreatedResponse,
  ApiOkResponse,
  ApiBody,
  ApiConsumes,
  ApiBearerAuth,
} from '@nestjs/swagger';
import { AdminService } from '../services/admin.service';
import { CreateMappingDto } from '../dto/create-mapping.dto';
import { UpdateMappingDto } from '../dto/update-mapping.dto';
import { CsvImportService } from '../../queues/services/csv-import.service';
import { UseGuards } from '@nestjs/common';
import { JwtAuthGuard } from '../../auth/guards/jwt-auth.guard';

@ApiTags('Admin')
@Controller('api/v1/admin')
@SkipThrottle()
@ApiBearerAuth('access-token')
@UseGuards(JwtAuthGuard)
export class AdminController {
  constructor(
    private readonly adminService: AdminService,
    private readonly csvImportService: CsvImportService,
  ) {}

  @Get('mappings')
  @ApiOperation({
    summary: 'List all tire mappings',
    description: 'Returns all mappings with size data and optional variants.',
  })
  @ApiOkResponse({
    description: 'Mappings retrieved successfully',
    schema: {
      example: [
        {
          id: 'uuid-v4',
          codePublic: '107',
          sizeRaw: '265/70R17',
          sizeNormalized: '265/70R17',
          variants: [
            { loadIndex: 91, speedIndex: 'V' },
            { loadIndex: 94, speedIndex: 'W' },
          ],
        },
      ],
    },
  })
  async listMappings() {
    return this.adminService.listMappings();
  }

  @Post('mappings')
  @ApiOperation({
    summary: 'Create a new tire mapping',
    description:
      'Create a new mapping. The public code is auto-generated and immutable.',
  })
  @ApiBody({
    type: CreateMappingDto,
    description: 'Mapping data (size only; code is generated by DB)',
  })
  @ApiCreatedResponse({
    description: 'Tire mapping created successfully',
    schema: {
      example: {
        id: 'uuid-v4',
        codePublic: '100',
        sizeRaw: '205/55R16',
        sizeNormalized: '205/55R16',
      },
    },
  })
  @ApiResponse({
    status: 400,
    description: 'Bad request - invalid format or missing fields',
  })
  @ApiResponse({
    status: 409,
    description: 'Conflict - code or size already exists',
  })
  async createMapping(@Body() body: CreateMappingDto) {
    return this.adminService.createMapping(body);
  }

  @Patch('mappings/:id')
  @ApiOperation({
    summary: 'Update an existing tire mapping',
    description: 'Update the size or variant data. Public codes are immutable.',
  })
  @ApiParam({
    name: 'id',
    description: 'Mapping ID (UUID)',
    example: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
  })
  @ApiBody({
    type: UpdateMappingDto,
    description: 'Fields to update (optional)',
  })
  @ApiResponse({
    status: 200,
    description: 'Tire mapping updated successfully',
    schema: {
      example: {
        id: 'uuid-v4',
        codePublic: '100',
        sizeRaw: '205/55R16',
        sizeNormalized: '205/55R16',
      },
    },
  })
  @ApiResponse({
    status: 400,
    description: 'Bad request - no fields provided',
  })
  @ApiResponse({
    status: 404,
    description: 'Mapping not found',
  })
  @ApiResponse({
    status: 409,
    description: 'Conflict - code or size already exists',
  })
  async updateMapping(@Param('id') id: string, @Body() body: UpdateMappingDto) {
    return this.adminService.updateMapping(id, body);
  }

  @Delete('mappings/:id')
  @ApiOperation({
    summary: 'Delete a tire mapping',
    description: 'Permanently delete a tire mapping by ID.',
  })
  @ApiParam({
    name: 'id',
    description: 'Mapping ID (UUID)',
    example: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
  })
  @ApiResponse({
    status: 200,
    description: 'Tire mapping deleted successfully',
    schema: {
      example: {
        id: 'uuid-v4',
        codePublic: '100',
        sizeRaw: '205/55R16',
        sizeNormalized: '205/55R16',
      },
    },
  })
  @ApiResponse({
    status: 404,
    description: 'Mapping not found',
  })
  async deleteMapping(@Param('id') id: string) {
    return this.adminService.deleteMapping(id);
  }

  @Post('import')
  @ApiOperation({
    summary: 'Import tire mappings from CSV',
    description:
      'Upload a CSV file to bulk import tire mappings. The file must contain columns: size, loadIndex (optional), speedIndex (optional). Codes are auto-generated. Processing happens in background.',
  })
  @ApiConsumes('multipart/form-data')
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        file: {
          type: 'string',
          format: 'binary',
          description: 'CSV file with tire mappings',
        },
      },
    },
  })
  @ApiCreatedResponse({
    description: 'CSV upload accepted, processing started',
    schema: {
      example: {
        jobId: 'job-uuid-v4',
        message: 'CSV import job created',
        rowCount: 100,
      },
    },
  })
  @ApiResponse({
    status: 400,
    description: 'Bad request - invalid CSV format or missing file',
  })
  @UseInterceptors(FileInterceptor('file'))
  async importCsv(@UploadedFile() file: Express.Multer.File) {
    if (!file) {
      throw new BadRequestException('No file uploaded');
    }

    if (!file.originalname.endsWith('.csv')) {
      throw new BadRequestException('File must be a CSV');
    }

    const content = file.buffer.toString('utf-8');

    try {
      const rows = this.csvImportService.parseCsvContent(content);
      const jobId = await this.csvImportService.addImportJob(rows);

      return {
        jobId,
        message: 'CSV import job created',
        rowCount: rows.length,
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      throw new BadRequestException(message);
    }
  }

  @Get('import/:jobId')
  @ApiOperation({
    summary: 'Get CSV import job status',
    description: 'Check the status and progress of a CSV import job.',
  })
  @ApiParam({
    name: 'jobId',
    description: 'Job ID returned from the import endpoint',
    example: 'job-uuid-v4',
  })
  @ApiResponse({
    status: 200,
    description: 'Job status retrieved',
    schema: {
      example: {
        id: 'job-uuid-v4',
        state: 'completed',
        progress: { current: 100, total: 100 },
        result: {
          processed: 95,
          errors: ['Row 12: Invalid format', 'Row 45: Missing size'],
        },
      },
    },
  })
  @ApiResponse({
    status: 404,
    description: 'Job not found',
  })
  async getImportStatus(@Param('jobId') jobId: string) {
    try {
      return await this.csvImportService.getJobStatus(jobId);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      throw new BadRequestException(message);
    }
  }
}
